# Generated by Django 3.2 on 2023-06-13 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Неподходящий логин. "me" использовать запрещено.', regex='^(?!me$).*$')], verbose_name='Логин'),
        ),
    ]
