# Generated by Django 3.2 on 2023-06-14 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_comments_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Наименоввание'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023, message='Год не должен быть больше текущего')], verbose_name='год создания'),
        ),
    ]
